"""Scout - derives doc-aware Matches from uploaded docs + the 4 primitives.

Public contract: consumers import from this package root only.
Internals (`stages/`, helpers) are not part of the contract.

Scout parses docs for drift context, searches per shared attribute
variable, and emits doc-aware Matches.
"""

from .contract import result_from_target_review
from .models import (
    available_configs,
    Attribute,
    ComparisonRule,
    ConformityScore,
    QuantitativeTarget,
    QuantitativeFieldLink,
    QuantitativeLedger,
    QuantitativeLedgerReview,
    QuantitativeStatementDisposition,
    DocumentSpan,
    SemanticSlot,
    SemanticDimensionAssessment,
    MeasurementSemanticAssessment,
    EvidenceUnitIdentity,
    TernaryDecision,
    DevelopmentProgram,
    DocumentContextValidation,
    EvidenceAssessment,
    EvidenceEntity,
    FunnelStats,
    Insight,
    LLMClientProtocol,
    Match,
    Measurement,
    NumericExpression,
    SourcePassageDisposition,
    ScoutResult,
    ScoutTypeConfig,
    SafetyObservation,
    PrecedentSignal,
    QueryIntent,
    QUANTITATIVE_SEMANTIC_FIELDS,
    SearchTrace,
    VALID_EVIDENCE_STRENGTHS,
    VALID_CONTEXT_STATUSES,
    VALID_PRECEDENT,
    VALID_PRECEDENT_OUTCOMES,
    VALID_RELATIONS,
    assessments_to_dicts,
    blocks_to_dicts,
    conformity_to_dicts,
    development_programs_to_dicts,
    find_config,
    load_attributes,
    load_config,
    matches_to_dicts,
    precedents_to_dicts,
    IndicatorReading,
    safety_observations_to_dicts,
)
from .pipeline import continue_pipeline, run_pipeline

__all__ = [
    "available_configs",
    "result_from_target_review",
    "Attribute",
    "ComparisonRule",
    "ConformityScore",
    "QuantitativeTarget",
    "QuantitativeFieldLink",
    "QuantitativeLedger",
    "QuantitativeLedgerReview",
    "QuantitativeStatementDisposition",
    "DocumentSpan",
    "SemanticSlot",
    "SemanticDimensionAssessment",
    "MeasurementSemanticAssessment",
    "EvidenceUnitIdentity",
    "TernaryDecision",
    "DevelopmentProgram",
    "DocumentContextValidation",
    "EvidenceAssessment",
    "EvidenceEntity",
    "FunnelStats",
    "Insight",
    "LLMClientProtocol",
    "Match",
    "Measurement",
    "NumericExpression",
    "SourcePassageDisposition",
    "ScoutResult",
    "ScoutTypeConfig",
    "SafetyObservation",
    "PrecedentSignal",
    "QueryIntent",
    "QUANTITATIVE_SEMANTIC_FIELDS",
    "SearchTrace",
    "VALID_EVIDENCE_STRENGTHS",
    "VALID_CONTEXT_STATUSES",
    "VALID_PRECEDENT",
    "VALID_PRECEDENT_OUTCOMES",
    "VALID_RELATIONS",
    "assessments_to_dicts",
    "blocks_to_dicts",
    "conformity_to_dicts",
    "development_programs_to_dicts",
    "find_config",
    "load_attributes",
    "load_config",
    "matches_to_dicts",
    "precedents_to_dicts",
    "IndicatorReading",
    "safety_observations_to_dicts",
    "continue_pipeline",
    "run_pipeline",
]
